[package]
name = "resource-monitor"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
opt-level = "s"
lto = true
# debug = true

[dependencies]
sysinfo = "0.32.0"
# sysinfo = "0.31.4"
gethostname = "0.5.0"
serde_json = "1.0.129"
serde = { version = "1.0.210", features = ["derive"] }
pnet = "0.35.0"
base64 = "0.22.1"
if-addrs = "0.13.3"
reqwest = { version = "0.12.8", features = ["blocking", "json"] }
threadpool = "1.8.1"

[target.x86_64-pc-windows-msvc.dependencies]
openssl = { version = "0.10.66", features = ["vendored"] }

[target.'cfg(unix)'.dependencies]
openssl = { version = "0.10.66", features = ["vendored"] }