[package]
name = "resource-monitor"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
opt-level = "s"
lto = true

[dependencies]
sysinfo = "0.31.2"
gethostname = "0.5.0"
serde_json = "1.0.117"
serde = { version = "1.0.203", features = ["derive"] }
pnet = "0.35.0"

