[package]
name = "resource-monitor"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
opt-level = "s"
lto = true

[dependencies]
sysinfo = "0.31.2"
gethostname = "0.5.0"
serde_json = "1.0.125"
serde = { version = "1.0.208", features = ["derive"] }
pnet = "0.35.0"
if-addrs = "0.13.3"
reqwest = { version = "0.12.7", features = ["blocking", "json"] }

[target.x86_64-pc-windows-msvc.dependencies]
openssl = { version = "0.10.66", features = ["vendored"] }

[target.'cfg(unix)'.dependencies]
openssl = { version = "0.10.66", features = ["vendored"] }