[package]
name = "resource-monitor"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
opt-level = "s"
lto = true

[dependencies]
sysinfo = "0.31.2"
gethostname = "0.5.0"
serde_json = "1.0.117"
serde = { version = "1.0.203", features = ["derive"] }
pnet = "0.35.0"
if-addrs = "0.13.2"
reqwest = { version = "0.12.1", features = ["blocking", "json"] }

[target.'cfg(windows)'.dependencies]
openssl = { version = "0.10.66", features = ["vendored"] }


[target.'cfg(unix)'.dependencies]
openssl = { version = "0.10.66", features = ["vendored"] }